### PR TITLE
Index template cleanup

### PR DESCRIPTION
**Pull request by panoptican**
- Since you aren't using that bold/italic webfont, you might as well leave it out to save on loading.
- Still had transitions on the glyphs so removed those. Don't want anyone thinking you know about CSS transitions. Next thing you know, they'll be asking you to make a [CSS Karl](https://codepen.io/Wujek_Greg/pen/EpJwaj).

### CODE REVIEW

**Comment by panoptican** [comment]
And nice work updating the template file. Was going to say that it should be pretty easy...

**Comment by craffel** [comment]
Thanks Jason.

> Since you aren't using that bold/italic webfont, you might as well leave it out to save on loading.

So if I end up having a 
```
<b><i>something</i></b>
```
 somewhere on my page someday, will the browser be smart enough to make it bold-italic on its own? Or should I add the webfont back in if that ever happens?

I also realized I don't need the style.css file anymore, right?

**Comment by panoptican** [comment]
You could add it back, but it would also just work. And yeah, you can ditch the `style.css` file.

**Comment by craffel** [comment]
Merged, thanks Jason.

**Pull request merged**
